name: bactipipe
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python >=3.7
  - fastp
  - spades
  - unicycler
  - flye
  - kmerfinder
  - nanoplot
  - filtlong
  - matplotlib
  - numpy
  - biopython
  - pysam
  - hmmer
  - prodigal
  - pplacer
  - checkm-genome
  - seqkit
  - pip
  - pip:
      - -e .
      - pyfastx
      - tqdm
      - colorama
      - textwrap3
      - psutil
      - setuptools
