name: bactipipe
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastp
  - spades
  - unicycler
  - flye
  - skesa
  - kmerfinder
  - filtlong
  - matplotlib
  - numpy
  - biopython
  - pysam
  - hmmer
  - prodigal
  - pplacer
  - checkm-genome
  - seqkit
  - pip
  - django
  - Celery
  - boto3
  - django-environ
  - awscli
  - skani
  - ska2
  - hcc::basespace-cli
  - pip:
      - -e .
      - redis
      - plotly
      - tqdm
      - colorama
      - textwrap3
      - psutil
      - setuptools
      - openpyxl
      - django-crispy-forms
      - crispy-bootstrap5
      - django-allauth
      - django-db-signals
      - django-celery-beat
      - psycopg2-binary    
      - django-grappelli
