name: bactipipe
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastp
  - spades
  - unicycler
  - flye
  - skesa
  - kmerfinder
  - filtlong
  - matplotlib
  - numpy
  - biopython
  - hmmer
  - prodigal
  - pplacer
  - checkm-genome
  - seqkit
  - pip
  - boto3
  - awscli
  - skani
  - ska2
  - hcc::basespace-cli
  - pip:
      - -e .
      - plotly
      - tqdm
      - colorama
      - textwrap3
      - psutil
      - setuptools
      - openpyxl

